version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - mode: host
        target: 80
        published: 80
        protocol: tcp
    networks:
      - network
    volumes:
      - /home/xodzm3131/nginx.conf:/etc/nginx/nginx.conf
      - static:/data/static/
      - media:/data/media/
      - log:/var/log/nginx/
    secrets:
      - NGINX_AUTH

  goaccess:
    image: allinurl/goaccess:1.5.1
    ports:
      - 7890:7890
    volumes:
      - log:/var/log/nginx/
    command: /var/log/nginx/tim_access.log -o /var/log/nginx/report.html --real-time-html --log-format COMBINED

  django:
    image: tim_django:7
    networks:
      - network
    volumes:
      - static:/home/gis_4ban_timproject22/staticfiles/
      - media:/home/gis_4ban_timproject22/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - network
    volumes:
      - mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  network:

volumes:
  static:
  media:
  mariadb:
  log:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  NGINX_AUTH:
    external: true