version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - network
    volumes:
      - /home/xodzm3131/nginx.conf:/etc/nginx/nginx.conf
      - static:/data/static/
      - media:/data/media/

  django:
    image: tim_django:4
    networks:
      - network
    volumes:
      - static:/home/gis_4ban_timproject22/staticfiles/
      - media:/home/gis_4ban_timproject22/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - network
    volumes:
      - mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234

networks:
  network:

volumes:
  static:
  media:
  mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true